/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity;


import java.util.Arrays;
import java.util.List;

import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.example.careercoachbookingsystem.entity.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Careercoachbooking extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>careercoachbooking</code>
     */
    public static final Careercoachbooking CAREERCOACHBOOKING = new Careercoachbooking();

    /**
     * The table <code>careercoachbooking.booking</code>.
     */
    public final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>careercoachbooking.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Careercoachbooking() {
        super(DSL.name("careercoachbooking"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Booking.BOOKING,
            User.USER
        );
    }
}
