/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity;


import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in careercoachbooking.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BOOKING_IDX_STATUS = Internal.createIndex(DSL.name("idx_status"), Booking.BOOKING, new OrderField[] { Booking.BOOKING.STATUS }, false);
    public static final Index BOOKING_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), Booking.BOOKING, new OrderField[] { Booking.BOOKING.USER_ID }, false);
}
