/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity;


import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.example.careercoachbookingsystem.entity.tables.User;
import org.example.careercoachbookingsystem.entity.tables.records.BookingRecord;
import org.example.careercoachbookingsystem.entity.tables.records.UserRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * careercoachbooking.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookingRecord> KEY_BOOKING_PRIMARY = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_PRIMARY"), new TableField[] { Booking.BOOKING.BOOKING_ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.USER_ID }, true);
}
