/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity;


import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.example.careercoachbookingsystem.entity.tables.User;


/**
 * Convenience access to all tables in careercoachbooking.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>careercoachbooking.booking</code>.
     */
    public static final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>careercoachbooking.user</code>.
     */
    public static final User USER = User.USER;
}
