/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables.records;


import java.time.LocalDateTime;

import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingRecord extends UpdatableRecordImpl<BookingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>careercoachbooking.booking.booking_id</code>. Cal.com
     * 返回的预约唯一ID
     */
    public BookingRecord setBookingId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.booking_id</code>. Cal.com
     * 返回的预约唯一ID
     */
    public String getBookingId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>careercoachbooking.booking.user_id</code>. 关联的用户ID
     */
    public BookingRecord setUserId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.user_id</code>. 关联的用户ID
     */
    public String getUserId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>careercoachbooking.booking.coach_name</code>. 导师姓名
     */
    public BookingRecord setCoachName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.coach_name</code>. 导师姓名
     */
    public String getCoachName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>careercoachbooking.booking.coach_email</code>. 导师邮箱
     */
    public BookingRecord setCoachEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.coach_email</code>. 导师邮箱
     */
    public String getCoachEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>careercoachbooking.booking.start_time</code>. 预约开始时间
     */
    public BookingRecord setStartTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.start_time</code>. 预约开始时间
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>careercoachbooking.booking.end_time</code>. 预约结束时间
     */
    public BookingRecord setEndTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.end_time</code>. 预约结束时间
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>careercoachbooking.booking.status</code>. 预约状态: PENDING,
     * BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
     */
    public BookingRecord setStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.status</code>. 预约状态: PENDING,
     * BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>careercoachbooking.booking.cancel_url</code>. 去取消预约的URL
     */
    public BookingRecord setCancelUrl(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.cancel_url</code>. 去取消预约的URL
     */
    public String getCancelUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>careercoachbooking.booking.created_at</code>.
     */
    public BookingRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>careercoachbooking.booking.updated_at</code>.
     */
    public BookingRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRecord
     */
    public BookingRecord() {
        super(Booking.BOOKING);
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(String bookingId, String userId, String coachName, String coachEmail, LocalDateTime startTime, LocalDateTime endTime, String status, String cancelUrl, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Booking.BOOKING);

        setBookingId(bookingId);
        setUserId(userId);
        setCoachName(coachName);
        setCoachEmail(coachEmail);
        setStartTime(startTime);
        setEndTime(endTime);
        setStatus(status);
        setCancelUrl(cancelUrl);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(org.example.careercoachbookingsystem.entity.tables.pojos.Booking value) {
        super(Booking.BOOKING);

        if (value != null) {
            setBookingId(value.getBookingId());
            setUserId(value.getUserId());
            setCoachName(value.getCoachName());
            setCoachEmail(value.getCoachEmail());
            setStartTime(value.getStartTime());
            setEndTime(value.getEndTime());
            setStatus(value.getStatus());
            setCancelUrl(value.getCancelUrl());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
