/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables.records;


import java.time.LocalDateTime;

import org.example.careercoachbookingsystem.entity.tables.User;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>careercoachbooking.user.user_id</code>. 用户唯一标识
     */
    public UserRecord setUserId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.user_id</code>. 用户唯一标识
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>careercoachbooking.user.name</code>. 用户姓名
     */
    public UserRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.name</code>. 用户姓名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>careercoachbooking.user.email</code>. 用户邮箱
     */
    public UserRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.email</code>. 用户邮箱
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>careercoachbooking.user.created_at</code>. 创建时间
     */
    public UserRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String userId, String name, String email, LocalDateTime createdAt) {
        super(User.USER);

        setUserId(userId);
        setName(name);
        setEmail(email);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(org.example.careercoachbookingsystem.entity.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setUserId(value.getUserId());
            setName(value.getName());
            setEmail(value.getEmail());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
