/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables.daos;


import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.example.careercoachbookingsystem.entity.tables.Booking;
import org.example.careercoachbookingsystem.entity.tables.records.BookingRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingDao extends DAOImpl<BookingRecord, org.example.careercoachbookingsystem.entity.tables.pojos.Booking, String> {

    /**
     * Create a new BookingDao without any configuration
     */
    public BookingDao() {
        super(Booking.BOOKING, org.example.careercoachbookingsystem.entity.tables.pojos.Booking.class);
    }

    /**
     * Create a new BookingDao with an attached configuration
     */
    public BookingDao(Configuration configuration) {
        super(Booking.BOOKING, org.example.careercoachbookingsystem.entity.tables.pojos.Booking.class, configuration);
    }

    @Override
    public String getId(org.example.careercoachbookingsystem.entity.tables.pojos.Booking object) {
        return object.getBookingId();
    }

    /**
     * Fetch records that have <code>booking_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfBookingId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.BOOKING_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>booking_id IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByBookingId(String... values) {
        return fetch(Booking.BOOKING.BOOKING_ID, values);
    }

    /**
     * Fetch a unique record that has <code>booking_id = value</code>
     */
    public org.example.careercoachbookingsystem.entity.tables.pojos.Booking fetchOneByBookingId(String value) {
        return fetchOne(Booking.BOOKING.BOOKING_ID, value);
    }

    /**
     * Fetch a unique record that has <code>booking_id = value</code>
     */
    public Optional<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchOptionalByBookingId(String value) {
        return fetchOptional(Booking.BOOKING.BOOKING_ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByUserId(String... values) {
        return fetch(Booking.BOOKING.USER_ID, values);
    }

    /**
     * Fetch records that have <code>coach_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfCoachName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.COACH_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>coach_name IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByCoachName(String... values) {
        return fetch(Booking.BOOKING.COACH_NAME, values);
    }

    /**
     * Fetch records that have <code>coach_email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfCoachEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.COACH_EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>coach_email IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByCoachEmail(String... values) {
        return fetch(Booking.BOOKING.COACH_EMAIL, values);
    }

    /**
     * Fetch records that have <code>start_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfStartTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Booking.BOOKING.START_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByStartTime(LocalDateTime... values) {
        return fetch(Booking.BOOKING.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfEndTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Booking.BOOKING.END_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByEndTime(LocalDateTime... values) {
        return fetch(Booking.BOOKING.END_TIME, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByStatus(String... values) {
        return fetch(Booking.BOOKING.STATUS, values);
    }

    /**
     * Fetch records that have <code>cancel_url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfCancelUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Booking.BOOKING.CANCEL_URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cancel_url IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByCancelUrl(String... values) {
        return fetch(Booking.BOOKING.CANCEL_URL, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Booking.BOOKING.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Booking.BOOKING.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Booking.BOOKING.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<org.example.careercoachbookingsystem.entity.tables.pojos.Booking> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Booking.BOOKING.UPDATED_AT, values);
    }
}
