/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Booking implements Serializable {

    private static final long serialVersionUID = 1L;

    private String bookingId;
    private String userId;
    private String coachName;
    private String coachEmail;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private String status;
    private String cancelUrl;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Booking() {}

    public Booking(Booking value) {
        this.bookingId = value.bookingId;
        this.userId = value.userId;
        this.coachName = value.coachName;
        this.coachEmail = value.coachEmail;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.status = value.status;
        this.cancelUrl = value.cancelUrl;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Booking(
        String bookingId,
        String userId,
        String coachName,
        String coachEmail,
        LocalDateTime startTime,
        LocalDateTime endTime,
        String status,
        String cancelUrl,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.bookingId = bookingId;
        this.userId = userId;
        this.coachName = coachName;
        this.coachEmail = coachEmail;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.cancelUrl = cancelUrl;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>careercoachbooking.booking.booking_id</code>. Cal.com
     * 返回的预约唯一ID
     */
    public String getBookingId() {
        return this.bookingId;
    }

    /**
     * Setter for <code>careercoachbooking.booking.booking_id</code>. Cal.com
     * 返回的预约唯一ID
     */
    public Booking setBookingId(String bookingId) {
        this.bookingId = bookingId;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.user_id</code>. 关联的用户ID
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>careercoachbooking.booking.user_id</code>. 关联的用户ID
     */
    public Booking setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.coach_name</code>. 导师姓名
     */
    public String getCoachName() {
        return this.coachName;
    }

    /**
     * Setter for <code>careercoachbooking.booking.coach_name</code>. 导师姓名
     */
    public Booking setCoachName(String coachName) {
        this.coachName = coachName;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.coach_email</code>. 导师邮箱
     */
    public String getCoachEmail() {
        return this.coachEmail;
    }

    /**
     * Setter for <code>careercoachbooking.booking.coach_email</code>. 导师邮箱
     */
    public Booking setCoachEmail(String coachEmail) {
        this.coachEmail = coachEmail;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.start_time</code>. 预约开始时间
     */
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>careercoachbooking.booking.start_time</code>. 预约开始时间
     */
    public Booking setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.end_time</code>. 预约结束时间
     */
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>careercoachbooking.booking.end_time</code>. 预约结束时间
     */
    public Booking setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.status</code>. 预约状态: PENDING,
     * BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>careercoachbooking.booking.status</code>. 预约状态: PENDING,
     * BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
     */
    public Booking setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.cancel_url</code>. 去取消预约的URL
     */
    public String getCancelUrl() {
        return this.cancelUrl;
    }

    /**
     * Setter for <code>careercoachbooking.booking.cancel_url</code>. 去取消预约的URL
     */
    public Booking setCancelUrl(String cancelUrl) {
        this.cancelUrl = cancelUrl;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>careercoachbooking.booking.created_at</code>.
     */
    public Booking setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.booking.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>careercoachbooking.booking.updated_at</code>.
     */
    public Booking setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Booking other = (Booking) obj;
        if (this.bookingId == null) {
            if (other.bookingId != null)
                return false;
        }
        else if (!this.bookingId.equals(other.bookingId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.coachName == null) {
            if (other.coachName != null)
                return false;
        }
        else if (!this.coachName.equals(other.coachName))
            return false;
        if (this.coachEmail == null) {
            if (other.coachEmail != null)
                return false;
        }
        else if (!this.coachEmail.equals(other.coachEmail))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.cancelUrl == null) {
            if (other.cancelUrl != null)
                return false;
        }
        else if (!this.cancelUrl.equals(other.cancelUrl))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.bookingId == null) ? 0 : this.bookingId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.coachName == null) ? 0 : this.coachName.hashCode());
        result = prime * result + ((this.coachEmail == null) ? 0 : this.coachEmail.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.cancelUrl == null) ? 0 : this.cancelUrl.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Booking (");

        sb.append(bookingId);
        sb.append(", ").append(userId);
        sb.append(", ").append(coachName);
        sb.append(", ").append(coachEmail);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(status);
        sb.append(", ").append(cancelUrl);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
