/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String userId;
    private String name;
    private String email;
    private LocalDateTime createdAt;

    public User() {}

    public User(User value) {
        this.userId = value.userId;
        this.name = value.name;
        this.email = value.email;
        this.createdAt = value.createdAt;
    }

    public User(
        String userId,
        String name,
        String email,
        LocalDateTime createdAt
    ) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>careercoachbooking.user.user_id</code>. 用户唯一标识
     */
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>careercoachbooking.user.user_id</code>. 用户唯一标识
     */
    public User setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.name</code>. 用户姓名
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>careercoachbooking.user.name</code>. 用户姓名
     */
    public User setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.email</code>. 用户邮箱
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>careercoachbooking.user.email</code>. 用户邮箱
     */
    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>careercoachbooking.user.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>careercoachbooking.user.created_at</code>. 创建时间
     */
    public User setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
