/*
 * This file is generated by jOOQ.
 */
package org.example.careercoachbookingsystem.entity.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.example.careercoachbookingsystem.entity.Careercoachbooking;
import org.example.careercoachbookingsystem.entity.Indexes;
import org.example.careercoachbookingsystem.entity.Keys;
import org.example.careercoachbookingsystem.entity.tables.records.BookingRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Booking extends TableImpl<BookingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>careercoachbooking.booking</code>
     */
    public static final Booking BOOKING = new Booking();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookingRecord> getRecordType() {
        return BookingRecord.class;
    }

    /**
     * The column <code>careercoachbooking.booking.booking_id</code>. Cal.com
     * 返回的预约唯一ID
     */
    public final TableField<BookingRecord, String> BOOKING_ID = createField(DSL.name("booking_id"), SQLDataType.VARCHAR(64).nullable(false), this, "Cal.com 返回的预约唯一ID");

    /**
     * The column <code>careercoachbooking.booking.user_id</code>. 关联的用户ID
     */
    public final TableField<BookingRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(64).nullable(false), this, "关联的用户ID");

    /**
     * The column <code>careercoachbooking.booking.coach_name</code>. 导师姓名
     */
    public final TableField<BookingRecord, String> COACH_NAME = createField(DSL.name("coach_name"), SQLDataType.VARCHAR(100).nullable(false), this, "导师姓名");

    /**
     * The column <code>careercoachbooking.booking.coach_email</code>. 导师邮箱
     */
    public final TableField<BookingRecord, String> COACH_EMAIL = createField(DSL.name("coach_email"), SQLDataType.VARCHAR(100).nullable(false), this, "导师邮箱");

    /**
     * The column <code>careercoachbooking.booking.start_time</code>. 预约开始时间
     */
    public final TableField<BookingRecord, LocalDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "预约开始时间");

    /**
     * The column <code>careercoachbooking.booking.end_time</code>. 预约结束时间
     */
    public final TableField<BookingRecord, LocalDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "预约结束时间");

    /**
     * The column <code>careercoachbooking.booking.status</code>. 预约状态: PENDING,
     * BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW
     */
    public final TableField<BookingRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "预约状态: PENDING, BOOKING_CREATED, BOOKING_CANCELLED, MEETING_ENDED, NO_SHOW");

    /**
     * The column <code>careercoachbooking.booking.cancel_url</code>. 去取消预约的URL
     */
    public final TableField<BookingRecord, String> CANCEL_URL = createField(DSL.name("cancel_url"), SQLDataType.CLOB(65535), this, "去取消预约的URL");

    /**
     * The column <code>careercoachbooking.booking.created_at</code>.
     */
    public final TableField<BookingRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>careercoachbooking.booking.updated_at</code>.
     */
    public final TableField<BookingRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Booking(Name alias, Table<BookingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Booking(Name alias, Table<BookingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>careercoachbooking.booking</code> table reference
     */
    public Booking(String alias) {
        this(DSL.name(alias), BOOKING);
    }

    /**
     * Create an aliased <code>careercoachbooking.booking</code> table reference
     */
    public Booking(Name alias) {
        this(alias, BOOKING);
    }

    /**
     * Create a <code>careercoachbooking.booking</code> table reference
     */
    public Booking() {
        this(DSL.name("booking"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Careercoachbooking.CAREERCOACHBOOKING;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.BOOKING_IDX_STATUS, Indexes.BOOKING_IDX_USER_ID);
    }

    @Override
    public UniqueKey<BookingRecord> getPrimaryKey() {
        return Keys.KEY_BOOKING_PRIMARY;
    }

    @Override
    public Booking as(String alias) {
        return new Booking(DSL.name(alias), this);
    }

    @Override
    public Booking as(Name alias) {
        return new Booking(alias, this);
    }

    @Override
    public Booking as(Table<?> alias) {
        return new Booking(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Booking rename(String name) {
        return new Booking(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Booking rename(Name name) {
        return new Booking(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Booking rename(Table<?> name) {
        return new Booking(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking where(Condition condition) {
        return new Booking(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Booking where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Booking where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Booking where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Booking where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Booking whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
